### PR TITLE
new ch-based measures

### PR DESCRIPTION
**Pull request by Heydon**
Added utility classes for various "measures" (widths based on text characters). This also widens the center column in the page layout as requested.

### CODE REVIEW

**Comment by VirginiaDooley** [comment]
This looks great, thanks @Heydon . @symroe ok with you?

**Comment by symroe** [comment]
I think this is useful to have, but that we should be really careful about using `ds-width-full` and `ds-width-full-text` in most contexts.

I feel like the design system should have _opinions_ about widths!

I'm quite sensitive to wide blocks of text. I think the slightly wider `measure` is a good change though, it's still narrow enough to be readable for me, but gives a little more space to the content :+1:

**Comment by Heydon** [comment]
@symroe Yeah, the utility classes are a last resort. But it is already opinionated in the sense that `ds-width-full-text` caps the characters per line to a readable length.

**Comment by symroe** [comment]
Super!

**Review by symroe — APPROVED** [review]

**Pull request merged**
